package X;

import java.util.List;
import java.util.Set;

/* renamed from: X.06R, reason: invalid class name */
/* loaded from: classes.dex */
public abstract class C06R extends AbstractC018408e {
    public static final Set A02;
    public static final Set A03;
    public static final Set A04;
    public static final Set A05;
    public static final Set A06;
    public static final Set A07;
    public static final List A01 = C00K.A03(AbstractC018408e.A01, C00G.A01("com.facebook.mk", "com.oculus.horizon.dev", "com.oculus.panelapp.settings", "com.oculus.shellenv", "com.facebook.games", "com.facebook.home.dev", "com.facebook.bonfire", "com.facebook.workdev", "com.facebook.home", "com.facebook.phone", "com.facebook.stella_debug", "com.facebook.mlite", "com.facebook.akira", "com.facebook.appmanager.dev", "com.facebook.daykira", "com.facebook.wearable.monza", "com.instagram.direct", "com.facebook.wakizashi", "com.facebook.horizon", "com.facebook.react.panelapp", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging", "com.meta.mr.awe", "com.meta.ar.arshellux", "com.oculus.vrshell.home", "com.oculus.externaldisplayservice", "com.facebook.orca.debug", "com.instagram.android.debug"));
    public static final List A00 = C00K.A03(AbstractC018408e.A00, C00G.A01("com.facebook.globalsecurity", "com.facebook.mlite_debug", "com.oculus.rooms", "com.facebook.horizon", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging", "com.facebook.orca.debug", "com.instagram.android.debug"));

    static {
        String[] strArr = new String[57];
        strArr[0] = "com.facebook.adsmanager";
        strArr[1] = "com.facebook.akira";
        strArr[2] = "com.facebook.appmanager";
        strArr[3] = "com.facebook.appmanager.dev";
        strArr[4] = "com.facebook.arstudio.player";
        strArr[5] = "com.facebook.assistantplayground";
        strArr[6] = "com.facebook.bishop";
        strArr[7] = "com.facebook.pages.app";
        strArr[8] = "com.facebook.creatorstudio";
        strArr[9] = "com.facebook.daykira";
        strArr[10] = "com.instagram.direct";
        strArr[11] = "com.facebook.lite";
        strArr[12] = "com.facebook.games";
        strArr[13] = "com.facebook.phone";
        strArr[14] = "com.facebook.home";
        strArr[15] = "com.facebook.home.dev";
        strArr[16] = "com.instagram.android";
        strArr[17] = "com.instagram.lite";
        strArr[18] = "com.facebook.katana";
        strArr[19] = "com.facebook.orca";
        strArr[20] = "com.facebook.react.panelapp";
        strArr[21] = "com.facebook.talk";
        strArr[22] = "com.facebook.mk";
        strArr[23] = "com.facebook.mlite";
        strArr[24] = "com.facebook.wearable.monza";
        strArr[25] = "com.oculus.assistant";
        strArr[26] = "com.oculus.vrshell";
        strArr[27] = "com.oculus.firsttimenux";
        strArr[28] = "com.oculus.horizon";
        strArr[29] = "com.oculus.horizon.dev";
        strArr[30] = "com.oculus.gemini.upload";
        strArr[31] = "com.oculus.metacam";
        strArr[32] = "com.oculus.panelapp.settings";
        strArr[33] = "com.oculus.vrshell.home";
        strArr[34] = "com.oculus.ocms";
        strArr[35] = "com.oculus.systemutilities";
        strArr[36] = "com.oculus.twilight";
        strArr[37] = "com.oculus.userserver2";
        strArr[38] = "com.oculus.updater";
        strArr[39] = "com.oculus.systemux";
        strArr[40] = "com.oculus.xrstreamingclient";
        strArr[41] = "com.facebook.bonfire";
        strArr[42] = "com.facebook.stella";
        strArr[43] = "com.facebook.stella_debug";
        strArr[44] = "com.facebook.study";
        strArr[45] = "com.instagram.barcelona";
        strArr[46] = "com.instagram.basel";
        strArr[47] = "com.facebook.wakizashi";
        strArr[48] = "com.whatsapp";
        strArr[49] = "com.whatsapp.w4b";
        strArr[50] = "com.facebook.horizon";
        strArr[51] = "com.facebook.together.together.stable";
        AnonymousClass000.A0G("com.facebook.together.together.release_nightly", "com.facebook.together.together.stable", "com.facebook.together.together.staging", "com.facebook.orca.debug", strArr);
        strArr[56] = "com.instagram.android.debug";
        A03 = C00G.A01(strArr);
        String[] strArr2 = new String[67];
        strArr2[0] = "com.facebook.adsmanager";
        strArr2[1] = "com.facebook.akira";
        strArr2[2] = "com.facebook.appmanager";
        strArr2[3] = "com.facebook.appmanager.dev";
        strArr2[4] = "com.facebook.arstudio.player";
        strArr2[5] = "com.facebook.assistantplayground";
        strArr2[6] = "com.instagram.barcelona";
        strArr2[7] = "com.instagram.basel";
        strArr2[8] = "com.facebook.bishop";
        strArr2[9] = "com.facebook.pages.app";
        strArr2[10] = "com.facebook.creatorstudio";
        strArr2[11] = "com.facebook.daykira";
        strArr2[12] = "com.instagram.direct";
        strArr2[13] = "com.facebook.lite";
        strArr2[14] = "com.facebook.games";
        strArr2[15] = "com.facebook.phone";
        strArr2[16] = "com.facebook.home";
        strArr2[17] = "com.facebook.home.dev";
        AnonymousClass000.A0F("com.instagram.android", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", strArr2);
        strArr2[22] = "com.facebook.react.panelapp";
        strArr2[23] = "com.facebook.talk";
        strArr2[24] = "com.facebook.mk";
        strArr2[25] = "com.facebook.mlite";
        strArr2[26] = "com.facebook.wearable.system.data";
        strArr2[27] = "com.facebook.wearable.apps.mwear";
        strArr2[28] = "com.facebook.wearable.system.notification";
        strArr2[29] = "com.facebook.wearable.monza";
        strArr2[30] = "com.oculus.assistant";
        strArr2[31] = "com.oculus.captionservice";
        strArr2[32] = "com.oculus.vrshell";
        strArr2[33] = "com.oculus.firsttimenux";
        strArr2[34] = "com.oculus.horizon";
        strArr2[35] = "com.oculus.horizon.dev";
        strArr2[36] = "com.oculus.gemini.upload";
        strArr2[37] = "com.oculus.metacam";
        strArr2[38] = "com.oculus.panelapp.settings";
        strArr2[39] = "com.oculus.vrshell.home";
        strArr2[40] = "com.oculus.ocms";
        strArr2[41] = "com.oculus.q4bservice";
        strArr2[42] = "com.oculus.systemutilities";
        strArr2[43] = "com.oculus.twilight";
        strArr2[44] = "com.oculus.userserver2";
        strArr2[45] = "com.oculus.updater";
        strArr2[46] = "com.oculus.systemux";
        strArr2[47] = "com.oculus.xrstreamingclient";
        strArr2[48] = "com.oculus.companion.server";
        strArr2[49] = "com.facebook.bonfire";
        strArr2[50] = "com.facebook.stella";
        strArr2[51] = "com.facebook.stella_debug";
        AnonymousClass000.A0G("com.facebook.study", "com.instagram.barcelona", "com.instagram.basel", "com.facebook.wakizashi", strArr2);
        strArr2[56] = "com.facebook.wearable.system.launcher";
        strArr2[57] = "com.whatsapp";
        strArr2[58] = "com.whatsapp.w4b";
        strArr2[59] = "com.facebook.horizon";
        strArr2[60] = "com.facebook.together.together.stable";
        strArr2[61] = "com.facebook.together.together.release_nightly";
        strArr2[62] = "com.facebook.together.together.stable";
        strArr2[63] = "com.facebook.together.together.staging";
        strArr2[64] = "com.facebook.react.panelapp";
        strArr2[65] = "com.facebook.orca.debug";
        strArr2[66] = "com.instagram.android.debug";
        A02 = C00G.A01(strArr2);
        A07 = C00G.A01("com.facebook.work", "com.facebook.workdev", "com.facebook.workchat");
        A04 = C00G.A01("com.instagram.direct", "com.instagram.android", "com.instagram.lite", "com.instagram.barcelona", "com.instagram.basel");
        A06 = C00G.A01("com.whatsapp", "com.whatsapp.w4b");
        String[] strArr3 = new String[22];
        strArr3[0] = "com.oculus.assistant";
        strArr3[1] = "com.oculus.browser";
        strArr3[2] = "com.oculus.captionservice";
        strArr3[3] = "com.oculus.companion.server";
        strArr3[4] = "com.oculus.explore";
        strArr3[5] = "com.oculus.firsttimenux";
        strArr3[6] = "com.oculus.vrshell.home";
        strArr3[7] = "com.oculus.horizon";
        strArr3[8] = "com.oculus.horizon.dev";
        strArr3[9] = "com.oculus.metacam";
        strArr3[10] = "com.oculus.nux.ota";
        strArr3[11] = "com.oculus.ocms";
        strArr3[12] = "com.oculus.panelapp.settings";
        strArr3[13] = "com.oculus.updater";
        strArr3[14] = "com.oculus.q4bservice";
        strArr3[15] = "com.oculus.store";
        strArr3[16] = "com.oculus.systemux";
        strArr3[17] = "com.oculus.xrstreamingclient";
        AnonymousClass000.A0F("com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.externaldisplayservice", strArr3);
        A05 = C00G.A01(strArr3);
    }
}
